import type { Domain, TopicContent } from './types';

export const topicOrder: string[] = [
  "time",
  "experiences",
  "connection",
  "purpose",
  "creativity",
  "adventure",
  "love",
  "family",
  "health",
  "gratitude",
  "blessings",
  "mind",
  "knowledge",
  "wisdom",
  "happiness",
  "curiosity",
  "kindness",
  "empathy",
  "contentment",
  "resilience",
  "community",
  "growth",
  "faith",
];

export const atlasDomains: Domain[] = [
  {
    name: "Inner Life",
    description: "The inner weather that shapes how you meet the world.",
    topics: ["mind", "contentment", "resilience", "faith", "wisdom"],
  },
  {
    name: "Relationships",
    description: "The forms of wealth that are built through attention, trust, and care.",
    topics: ["love", "family", "connection", "empathy", "kindness", "community"],
  },
  {
    name: "Vitality",
    description: "The conditions that give you energy, steadiness, and room to breathe.",
    topics: ["health", "time", "blessings", "gratitude"],
  },
  {
    name: "Growth",
    description: "The capacities that expand what you can understand, make, and become.",
    topics: ["knowledge", "curiosity", "creativity", "purpose", "growth"],
  },
  {
    name: "Living Fully",
    description: "The textures of a full life: memory, delight, novelty, and aliveness.",
    topics: ["adventure", "experiences", "happiness"],
  },
];

export const topicContent: Record<string, TopicContent> = {
  time: {
    title: "Time",
    domain: "Vitality",
    definition: "Time wealth means having enough space to direct your attention intentionally.",
    why: "A day can be full and still feel poor if it is fragmented beyond recognition. Time wealth is not about squeezing more in. It is about protecting what matters, reducing leakage, and making your hours look like your values.",
    notice: "Notice where your day gets spent by inertia instead of by choice.",
    choose: "Choose one block of time this week that deserves deliberate protection.",
    practice: "Put one meaningful activity on your calendar before the noise gets there first.",
    prompts: [
      "What part of your schedule feels owned by someone else?",
      "Which activity leaves you feeling more spacious afterward?",
      "What can you stop agreeing to for the next seven days?",
    ],
  },
  experiences: {
    title: "Experiences",
    domain: "Living Fully",
    definition: "Experience wealth means letting life contain texture, novelty, and memory.",
    why: "A rich life is not built from accumulation alone. It is built from moments that wake you up, teach you something, or stay with you years later. Experience wealth grows when you leave room for memorable days.",
    notice: "Notice when your weeks start to blur together into repeatable routines.",
    choose: "Choose one experience that will give this month a distinct shape.",
    practice: "Plan one specific outing, conversation, or experiment before the day ends.",
    prompts: [
      "What memory from the last year still feels alive in your body?",
      "What have you been postponing because it seems slightly inconvenient?",
      "What tiny adventure would make this week more vivid?",
    ],
  },
  connection: {
    title: "Connection",
    domain: "Relationships",
    definition: "Connection wealth means feeling genuinely linked to people, places, and reality.",
    why: "It is possible to be surrounded and still feel separate. Connection wealth comes from contact that is real enough to change your state: shared attention, honest conversation, and a sense that you are not moving through life alone.",
    notice: "Notice the difference between being updated on someone and actually feeling with them.",
    choose: "Choose one relationship that deserves more presence than convenience.",
    practice: "Send a message that opens a real exchange instead of a transactional check-in.",
    prompts: [
      "Who do you feel more yourself around?",
      "What usually interrupts your presence when you are with other people?",
      "Where in your life do you want more mutuality, not just contact?",
    ],
  },
  purpose: {
    title: "Purpose",
    domain: "Growth",
    definition: "Purpose wealth means knowing what deserves your effort right now.",
    why: "Purpose is not a grand slogan you discover once. It is a working orientation. It helps you decide what to pursue, what to refuse, and what kind of tiredness is worth it.",
    notice: "Notice which tasks drain you because they feel disconnected from any real aim.",
    choose: "Choose one responsibility that matters enough to deserve your best attention.",
    practice: "Write one sentence that explains why your current work matters to someone real.",
    prompts: [
      "What kind of contribution leaves you with clean fatigue instead of resentment?",
      "What are you saying yes to that does not belong to your deeper priorities?",
      "What would purpose look like at the scale of this week, not your whole life?",
    ],
  },
  creativity: {
    title: "Creativity",
    domain: "Growth",
    definition: "Creativity wealth means having room to make, combine, and express.",
    why: "Creativity is not reserved for artists. It is a way of relating to life that lets you shape something instead of only consuming what already exists. Creative wealth grows when you stay generative.",
    notice: "Notice how often you consume inspiration without turning any of it into output.",
    choose: "Choose one medium or problem where you want to make something imperfect but real.",
    practice: "Spend twenty focused minutes making a draft instead of collecting more inputs.",
    prompts: [
      "What do you keep wanting to make but rarely prioritize?",
      "What form of creativity feels playful rather than performative?",
      "Where have you confused polish with permission to begin?",
    ],
  },
  adventure: {
    title: "Adventure",
    domain: "Living Fully",
    definition: "Adventure wealth means choosing some uncertainty over total control.",
    why: "Adventure does not require extreme risk. It begins when you allow the unfamiliar to enter your life. A little uncertainty can restore alertness, courage, and gratitude for being alive.",
    notice: "Notice how quickly comfort becomes automatic and invisible.",
    choose: "Choose one situation where a little unpredictability would make you more awake.",
    practice: "Take a route, make a plan, or accept an invitation that slightly stretches your usual pattern.",
    prompts: [
      "What kind of risk makes you feel more alive rather than just unsafe?",
      "What would count as an adventure at your current season of life?",
      "Where are you over-optimizing for predictability?",
    ],
  },
  love: {
    title: "Love",
    domain: "Relationships",
    definition: "Love wealth means giving and receiving care with steadiness.",
    why: "Love is built less by intensity than by repeated acts of regard. Love wealth grows through presence, repair, generosity, and the willingness to let another person's wellbeing matter to you.",
    notice: "Notice the small moments when you can either turn toward someone or stay defended.",
    choose: "Choose one person to love more concretely this week.",
    practice: "Offer one act of care that reduces someone else's burden today.",
    prompts: [
      "Who feels safer because you are in their life?",
      "How do you usually withhold love when you feel tired or disappointed?",
      "What does dependable affection look like in practice?",
    ],
  },
  family: {
    title: "Family",
    domain: "Relationships",
    definition: "Family wealth means investing in the people you return to.",
    why: "Family wealth is not about perfection or sentimentality. It is about tending the ties that anchor you, whether inherited or chosen. It grows through rituals, repair, practical help, and memory.",
    notice: "Notice which family relationships feel undernourished rather than broken.",
    choose: "Choose one family bond that deserves more intentional tending.",
    practice: "Create or restart one small ritual that helps people stay in each other's lives.",
    prompts: [
      "What kind of family contact leaves you more grounded afterward?",
      "What does your family need more of: honesty, softness, or initiative?",
      "What inheritance do you want to strengthen or interrupt?",
    ],
  },
  health: {
    title: "Health",
    domain: "Vitality",
    definition: "Health wealth means having the energy to live your days well.",
    why: "Without health, many other forms of wealth become harder to enjoy or sustain. Health wealth is built through ordinary stewardship: sleep, movement, food, recovery, and the willingness to listen before the body has to shout.",
    notice: "Notice what your body has been asking for repeatedly.",
    choose: "Choose the health habit that would create the biggest downstream benefit if it stabilized.",
    practice: "Do the next obvious physical thing your future self will thank you for.",
    prompts: [
      "What behavior most affects your energy for the rest of the day?",
      "Which signal from your body have you normalized too quickly?",
      "What health action would make other good decisions easier?",
    ],
  },
  gratitude: {
    title: "Gratitude",
    domain: "Vitality",
    definition: "Gratitude wealth means noticing what is already supporting your life.",
    why: "Gratitude does not deny difficulty. It widens perception so hardship is not the only thing in view. Gratitude wealth changes the texture of a day by restoring proportion, sufficiency, and affection for what is already here.",
    notice: "Notice what you routinely benefit from without really registering it.",
    choose: "Choose one part of your life to appreciate in detail instead of in passing.",
    practice: "Name three specific supports from today and tell one person thank you.",
    prompts: [
      "What feels ordinary now that would have felt remarkable to an earlier version of you?",
      "Which person or system quietly makes your life easier every week?",
      "How does gratitude change your posture toward the rest of the day?",
    ],
  },
  blessings: {
    title: "Blessings",
    domain: "Vitality",
    definition: "Blessings wealth means recognizing gifts you did not earn alone.",
    why: "Some of what makes life possible arrives through grace, luck, timing, lineage, or help. Blessings wealth keeps you humble and receptive. It reminds you that not everything valuable is produced by effort alone.",
    notice: "Notice what in your life came partly through gift rather than control.",
    choose: "Choose one blessing you want to honor with more care.",
    practice: "Respond to one gift in your life by using it well or passing something on.",
    prompts: [
      "What advantage or tenderness have you received that still shapes your life?",
      "Which blessing have you started treating like a guarantee?",
      "How can gratitude become stewardship instead of just sentiment?",
    ],
  },
  mind: {
    title: "Mind",
    domain: "Inner Life",
    definition: "Mind wealth means cultivating clarity, attention, and inner steadiness.",
    why: "A crowded mind makes even good circumstances feel noisy. Mind wealth grows through reflection, concentration, perspective, and the habits that keep you from being dragged by every impulse or signal.",
    notice: "Notice what your attention is repeatedly getting captured by.",
    choose: "Choose one practice that helps your mind become quieter and more deliberate.",
    practice: "Spend ten uninterrupted minutes thinking, journaling, or sitting without input.",
    prompts: [
      "What currently fragments your attention the most?",
      "When do you feel mentally cleanest?",
      "What thought pattern needs less trust from you?",
    ],
  },
  knowledge: {
    title: "Knowledge",
    domain: "Growth",
    definition: "Knowledge wealth means building understanding you can apply and share.",
    why: "Information is cheap. Knowledge becomes wealth when it changes what you can see, explain, or do. It compounds through study, synthesis, and the discipline of revisiting what matters.",
    notice: "Notice the difference between collecting information and truly learning it.",
    choose: "Choose one subject worth understanding more deeply instead of skimming endlessly.",
    practice: "Study one idea long enough to explain it back in plain language.",
    prompts: [
      "What are you repeatedly curious about but only half-learning?",
      "What knowledge would genuinely improve your decisions this year?",
      "How can you turn passive intake into retained understanding?",
    ],
  },
  wisdom: {
    title: "Wisdom",
    domain: "Inner Life",
    definition: "Wisdom wealth means choosing well when life is ambiguous.",
    why: "Wisdom is not raw intelligence. It is judgment shaped by reflection, experience, patience, and humility. Wisdom wealth grows when you learn to see patterns, hold tradeoffs, and act without self-deception.",
    notice: "Notice where you are tempted to react before understanding the whole situation.",
    choose: "Choose one decision that deserves slower, calmer thinking.",
    practice: "Ask what is true, what matters, and what consequence you are underestimating.",
    prompts: [
      "Where do you already know the answer but resist it?",
      "What older lesson would help with a current problem?",
      "What would a wiser pace look like here?",
    ],
  },
  happiness: {
    title: "Happiness",
    domain: "Living Fully",
    definition: "Happiness wealth means making room for delight without making it a demand.",
    why: "Happiness is not the whole point of life, but life becomes thin when joy is always postponed. Happiness wealth grows through appreciation, play, beauty, relief, and the ability to receive good moments without suspicion.",
    notice: "Notice what reliably lifts your mood in a clean and durable way.",
    choose: "Choose one source of delight worth protecting from busyness.",
    practice: "Do one small thing today purely because it adds brightness to being alive.",
    prompts: [
      "What forms of joy leave you more open instead of more numb?",
      "Where have you made happiness too conditional?",
      "What simple pleasure have you outgrown only in theory?",
    ],
  },
  curiosity: {
    title: "Curiosity",
    domain: "Growth",
    definition: "Curiosity wealth means staying interested enough to keep learning.",
    why: "Curiosity keeps life from becoming inert. It fuels growth, conversation, humility, and surprise. Curious people notice more, ask better questions, and stay responsive to a changing world.",
    notice: "Notice where certainty has made you less observant than you think.",
    choose: "Choose one question that deserves exploration rather than a quick opinion.",
    practice: "Follow one thread of interest until you discover something you did not expect.",
    prompts: [
      "What topic have you secretly wanted to understand better?",
      "What question would make a conversation more alive?",
      "Where has defensiveness replaced interest?",
    ],
  },
  kindness: {
    title: "Kindness",
    domain: "Relationships",
    definition: "Kindness wealth means making life gentler for the people around you.",
    why: "Kindness is a form of practical abundance. It creates ease, dignity, and repair where harshness would multiply friction. Kindness wealth grows through habits of warmth, patience, and consideration.",
    notice: "Notice the moments where a small softness would materially improve someone's day.",
    choose: "Choose one setting where you want to be remembered as easier to be around.",
    practice: "Do one generous thing that costs little but changes the emotional temperature.",
    prompts: [
      "What does kindness look like when you are busy?",
      "Whom have you been treating with efficiency instead of warmth?",
      "How can you make your care more visible, not just assumed?",
    ],
  },
  empathy: {
    title: "Empathy",
    domain: "Relationships",
    definition: "Empathy wealth means sensing another person's experience without collapsing your own.",
    why: "Empathy widens your world. It helps you respond with accuracy instead of projection. Empathy wealth grows when you become more capable of listening, imagining, and making room for realities other than your own.",
    notice: "Notice when you start preparing your answer before the other person has really finished.",
    choose: "Choose one relationship where better understanding would matter more than being right.",
    practice: "Ask one follow-up question that helps someone feel more accurately seen.",
    prompts: [
      "What is harder for you: understanding pain or understanding difference?",
      "Where do you tend to substitute advice for attention?",
      "What would change if you assumed the other person makes sense from inside their experience?",
    ],
  },
  contentment: {
    title: "Contentment",
    domain: "Inner Life",
    definition: "Contentment wealth means feeling enoughness in the middle of ordinary life.",
    why: "Contentment is not passivity. It is freedom from the reflex that says life can only begin after the next acquisition or achievement. Contentment wealth makes the present inhabitable while you continue to grow.",
    notice: "Notice what your mind keeps insisting must change before you can relax.",
    choose: "Choose one area where enough would be healthier than more.",
    practice: "Pause long enough to enjoy one ordinary good thing without improving it.",
    prompts: [
      "What desire keeps promising relief but never quite delivers it?",
      "Where in your life is there already more than enough?",
      "What does sufficiency feel like in your body?",
    ],
  },
  resilience: {
    title: "Resilience",
    domain: "Inner Life",
    definition: "Resilience wealth means recovering without hardening.",
    why: "Resilience is not pretending things do not hurt. It is the capacity to bend, adapt, and repair while keeping your humanity intact. Resilience wealth is built through support, perspective, and repeated recovery.",
    notice: "Notice how you respond after setbacks: collapse, denial, or repair.",
    choose: "Choose one recovery habit that helps you return to yourself faster.",
    practice: "After the next stress spike, do one action that restores steadiness before you problem-solve.",
    prompts: [
      "What reliably helps you come back after a difficult day?",
      "Where have you confused toughness with resilience?",
      "Who helps you recover without pretending?",
    ],
  },
  community: {
    title: "Community",
    domain: "Relationships",
    definition: "Community wealth means belonging to circles of mutual care.",
    why: "Community turns private life into shared life. It gives support, accountability, celebration, and continuity. Community wealth grows when you participate instead of only consuming what others organize.",
    notice: "Notice where you already have weak ties that could become real belonging.",
    choose: "Choose one circle you want to contribute to instead of merely attending.",
    practice: "Make one concrete contribution that helps a group become more alive or functional.",
    prompts: [
      "Where do you feel welcomed, useful, and known?",
      "What kind of community do you wish existed more strongly around you?",
      "What would belonging require from you, not just provide to you?",
    ],
  },
  growth: {
    title: "Growth",
    domain: "Growth",
    definition: "Growth wealth means becoming more capable without losing your center.",
    why: "Growth is healthy when it enlarges your life rather than keeping you in permanent self-revision. Growth wealth is built through deliberate challenge, reflection, and the patience to improve over time.",
    notice: "Notice whether your current effort is stretching you or merely exhausting you.",
    choose: "Choose one edge where development would genuinely expand your life.",
    practice: "Take one repeatable step that moves you from intention into skill.",
    prompts: [
      "What kind of person are you trying to become through your current habits?",
      "Where would steady improvement matter more than intensity?",
      "What evidence would show that you are actually growing?",
    ],
  },
  faith: {
    title: "Faith",
    domain: "Inner Life",
    definition: "Faith wealth means trusting that meaning can exist beyond immediate proof.",
    why: "Faith is not only religious conviction. It can also mean trust, orientation, and a willingness to keep walking when certainty is unavailable. Faith wealth steadies action in seasons where evidence arrives slowly.",
    notice: "Notice where you demand certainty before taking the next honest step.",
    choose: "Choose one area where trust is healthier than endless control.",
    practice: "Take one small faithful action even if the whole path is still unclear.",
    prompts: [
      "What do you lean on when outcomes are uncertain?",
      "Where has fear disguised itself as rational delay?",
      "What would trust look like in practice this week?",
    ],
  },
};
